volumes:
  pipe: {}

services:
  pipe:
    image: alpine:3.16
    volumes:
      - pipe:/var/run/hwc-logstream
    command:
      - sh
      - -c
      - rm -f /var/run/hwc-logstream/pipe && mkfifo /var/run/hwc-logstream/pipe

  hwc-logstream:
    build: ".."
    depends_on:
      pipe:
        condition: service_completed_successfully
    environment:
      HUAWEICLOUD_SDK_AK:
      HUAWEICLOUD_SDK_SK:
      HUAWEICLOUD_SDK_PROJECT_ID:
      HUAWEICLOUD_SDK_DOMAIN_ID:
    volumes:
      - pipe:/var/run/hwc-logstream
    entrypoint: []
    command:
      - sh
      - -c
      - hwc-logstream > /var/run/hwc-logstream/pipe

  # Sidecar
  vector:
    image: timberio/vector:0.31.0-debian
    depends_on:
      pipe:
        condition: service_completed_successfully
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - pipe:/var/run/hwc-logstream
    entrypoint: []
    command:
      - sh
      - -c
      - vector -c /etc/vector/vector.toml < /var/run/hwc-logstream/pipe

  # Aggregator
  vector-aggregator:
    image: timberio/vector:0.31.0-debian
    volumes:
      - ./vector-aggregator.toml:/etc/vector/vector.toml:ro
      - ./vector-aggregator.vrl:/etc/vector/vector-aggregator.vrl:ro
    ports:
      - 8080:8080
