services:
  # stdin sidecars, pick one
  benthos:
    image: jeffail/benthos:4.18.0
    command: 
      -s "input.type=stdin" 
      -s "output.type=http_client" 
      -s "output.http_client.url=http://vector-aggregator:8080"
      -s "output.http_client.retries=9223372036854775807"
      -s "output.http_client.batching.byte_size=5000"
      -s "output.http_client.batching.count=1000"
      -s "output.http_client.batching.period=1s"
      
  vector:
    image: timberio/vector:0.31.0-debian
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro

  # HTTP log receiver
  vector-aggregator:
    image: timberio/vector:0.31.0-debian
    volumes:
      - ./vector-aggregator.toml:/etc/vector/vector.toml:ro
    ports: 
      - 8080:8080

  