[sources.hwc_lts_stream]
type = "http_server"
address = "0.0.0.0:8080"
decoding.codec = "json"
framing.method = "newline_delimited"

[transforms.remap]
type = "remap"
inputs = ["hwc_lts_stream"]
file = "/etc/vector/vector-aggregator.vrl"

[sinks.console]
type = "console"
inputs = ["remap"]
encoding.codec = "json"
framing.method = "newline_delimited"
